apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: ace-create-integration-server
spec:
  params:
    # --------------------------------------------------------------
    # details of the IntegrationRuntime to create
    # --------------------------------------------------------------
    - name: integration-name
      description: name to give the integration runtime
    - name: ace-namespace
      description: namespace to create the IntegrationRuntime in
    # --------------------------------------------------------------
    # what flavour of App Connect to run
    #  for details, see https://www.ibm.com/docs/en/app-connect/containers_cd?topic=obtaining-app-connect-enterprise-server-image-from-cloud-container-registry
    # --------------------------------------------------------------
    - name: ace-server-version
      description: version of App Connect Enterprise to use
    - name: ace-server-license
      description: ID of the license to use for the IntegrationRuntime
    # --------------------------------------------------------------
    # bar file to deploy
    # --------------------------------------------------------------
    - name: bar-url
      description: raw HTTPS URL to the BAR file in the git repository
    - name: barauth-configuration
      description: name of the barauth Configuration with git credentials
      default: "github-barauth"
    # --------------------------------------------------------------
    # optional arguments
    #   scaling
    # --------------------------------------------------------------
    - name: replicas
      default: 1
    # --------------------------------------------------------------
    # optional arguments
    #   Configuration resources that can be added to
    #    the integration runtime
    # --------------------------------------------------------------
    - name: policies-configuration
      description: name of the policies project to use
      default: ""
    - name: setdbparms-configuration
      description: name of the setdbparms configuration object to use
      default: ""
    - name: datasource-configuration
      description: name of the data source object to use
      default: ""
    - name: serverconf-configuration
      description: name of the server.conf.yaml configuration object to use
      default: ""
    - name: truststore-configuration
      description: name of the truststore configuration object to use
      default: ""
    # --------------------------------------------------------------

  workspaces:
    - name: output
      description: workspace with the resources

  steps:
    - name: run
      image: image-registry.openshift-image-registry.svc:5000/openshift/tools
      script: |
        #!/bin/sh

        set -e

        echo "preparing configuration list"
        BARAUTH_CONFIG="- $(params.barauth-configuration)"
        if [ -n "$(params.policies-configuration)" ]; then
          POLICIES_CONFIG="- $(params.policies-configuration)"
        fi
        if [ -n "$(params.setdbparms-configuration)" ]; then
          SETDBPARMS_CONFIG="- $(params.setdbparms-configuration)"
        fi
        if [ -n "$(params.datasource-configuration)" ]; then
          DATASOURCE_CONFIG="- $(params.datasource-configuration)"
        fi
        if [ -n "$(params.serverconf-configuration)" ]; then
          SERVERCONF_CONFIG="- $(params.serverconf-configuration)"
        fi
        if [ -n "$(params.truststore-configuration)" ]; then
          TRUSTSTORE_CONFIG="- $(params.truststore-configuration)"
        fi

        echo "creating integration runtime"
        oc apply -f - <<EOF
        apiVersion: appconnect.ibm.com/v1beta1
        kind: IntegrationRuntime
        metadata:
          name: $(params.integration-name)
          namespace: $(params.ace-namespace)
        spec:
          barURL:
            - $(params.bar-url)
          configurations:
            $BARAUTH_CONFIG
            $POLICIES_CONFIG
            $SETDBPARMS_CONFIG
            $DATASOURCE_CONFIG
            $SERVERCONF_CONFIG
            $TRUSTSTORE_CONFIG
          version: '$(params.ace-server-version)'
          license:
            accept: true
            license: $(params.ace-server-license)
            use: CloudPakForIntegrationProduction
          replicas: $(params.replicas)
        EOF
